name: Repo sync test

# See copybara GH action docs here for syncing a monorepo subdirectory to
# the root directory in another repo
# https://github.com/Olivr/copybara-action/blob/main/docs/basic-usage.md#subfolder-as-destinations-root

on:
- pull_request_target
- push

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: olivr/copybara-action@v1.2.3
      with:
        ssh_key: ${{ secrets.SYNC_SSH_KEY }}
        access_token: ${{ secrets.SYNC_TOKEN }}
        sot_repo: reka/private-repo-sync-test
        destination_repo: reka/repo-sync-test-public-2
        push_include: public/** .github/workflows/sync-public.yml
        pr_move: |
          ||public
          public/.github||.github
